// The identity data service over PostgreSQL: identity.data.Service served
// with connect-go, its statements generated by sqlc over pgx.
package main

import (
	"os"

	"github.com/authaas/identity-data-service-postgres-pgx-connect-go/internal/cli"
)

func main() {
	os.Exit(cli.Run())
}
